import { Route } from '../types.js';

export const coreRoutes: Route[] = [
  {
    name: 'coder',
    agentSlug: 'coder',
    threshold: 0.65,
    fallbackToLLM: true,
    description: 'General code implementation',
    utterances: [
      'implement the user registration feature',
      'write the function to calculate shipping costs',
      'code the database migration script',
      'build the REST API endpoint for creating orders',
      'implement the caching layer for the search results',
      'write the TypeScript interface for the user model',
      'code the background job for sending notification emails',
      'implement the file upload handler',
      'build the data transformation pipeline',
      'write the utility function for date formatting',
      'create the pagination logic for the list endpoint',
      'implement the retry mechanism for failed requests',
    ],
  },
  {
    name: 'reviewer',
    agentSlug: 'reviewer',
    threshold: 0.68,
    fallbackToLLM: true,
    description: 'Code review and quality assessment',
    utterances: [
      'review this pull request for code quality',
      'check this code for best practices violations',
      'review the implementation for potential issues',
      'give feedback on this TypeScript module',
      'check this function for edge cases and bugs',
      'review the database query for performance issues',
      'look over this class design and suggest improvements',
      'review the error handling in this module',
      'check this code against our coding standards',
      'evaluate the readability and maintainability of this code',
      'review this PR before merging',
      'critique the architecture of this service',
    ],
  },
  {
    name: 'tester',
    agentSlug: 'tester',
    threshold: 0.68,
    fallbackToLLM: true,
    description: 'Writing tests, test coverage analysis',
    utterances: [
      'write unit tests for the authentication module',
      'create integration tests for the payment API',
      'write Jest tests for this TypeScript class',
      'generate test cases for the user registration flow',
      'write end-to-end tests for the checkout process',
      'create test fixtures for the database layer',
      'write property-based tests for the validation logic',
      'generate mock data for testing the API endpoints',
      'write snapshot tests for these React components',
      'create the test harness for the background workers',
      'add test coverage for the edge cases in this function',
      'write regression tests to prevent this bug from recurring',
    ],
  },
  {
    name: 'researcher',
    agentSlug: 'researcher',
    threshold: 0.65,
    fallbackToLLM: true,
    description: 'Research, analysis, and investigation',
    utterances: [
      'research the best approach for implementing rate limiting',
      'investigate the root cause of this performance regression',
      'analyze the existing codebase architecture',
      'research alternatives to our current authentication approach',
      'investigate which database is best for this use case',
      'analyze the error patterns in the production logs',
      'research the state of the art for vector search',
      'investigate the security implications of this design',
      'analyze the token usage patterns across our agents',
      'research how other systems solve this distributed consensus problem',
      'explore the tradeoffs between these two architectural approaches',
      'gather requirements and constraints for the new feature',
    ],
  },
  {
    name: 'planner',
    agentSlug: 'planner',
    threshold: 0.65,
    fallbackToLLM: true,
    description: 'Task planning, roadmap creation, sprint planning',
    utterances: [
      'create a project plan for building the new feature',
      'break down this epic into actionable tasks',
      'plan the migration from monolith to microservices',
      'create a roadmap for the next quarter',
      'organize the backlog into prioritized sprints',
      'plan the rollout strategy for this change',
      'create a timeline for the API redesign',
      'define the milestones for this project',
      'plan the testing strategy for the release',
      'outline the steps needed to implement this architecture',
    ],
  },
];
