import { Route } from '../types.js';

export const designRoutes: Route[] = [
  {
    name: 'ui-designer',
    agentSlug: 'design-ui-designer',
    threshold: 0.70,
    fallbackToLLM: true,
    description: 'UI design, component design, design systems',
    utterances: [
      'design the UI for the user profile page',
      'create the component library for the design system',
      'design the dashboard layout with data visualization',
      'create the mobile UI mockups for the onboarding flow',
      'design the dark mode theme for the application',
      'create the icon set for the navigation menu',
      'design the empty state illustrations for the app',
      'create the loading skeleton screens for the content areas',
      'design the data table component with sorting and filtering',
      'create the notification toast component designs',
    ],
  },
  {
    name: 'ux-architect',
    agentSlug: 'design-ux-architect',
    threshold: 0.70,
    fallbackToLLM: true,
    description: 'UX architecture, information architecture, user flows',
    utterances: [
      'design the user flow for the checkout experience',
      'create the information architecture for the navigation',
      'design the onboarding experience for new users',
      'map the user journey for the subscription upgrade flow',
      'design the error recovery flow for payment failures',
      'create the sitemap and navigation hierarchy',
      'design the progressive disclosure pattern for complex forms',
      'architect the multi-step wizard for the setup process',
      'design the search and filter user experience',
      'create the user flow for the account settings management',
    ],
  },
  {
    name: 'ux-researcher',
    agentSlug: 'design-ux-researcher',
    threshold: 0.70,
    fallbackToLLM: true,
    description: 'UX research, user testing, usability analysis',
    utterances: [
      'conduct a usability study on the new checkout flow',
      'analyze the user interview findings for the product redesign',
      'create the user testing script for the prototype',
      'analyze heatmap and session recording data for insights',
      'conduct competitive analysis of the user experience',
      'synthesize the survey results into design recommendations',
      'create user personas based on the research data',
      'design the A/B test for the new landing page',
      'analyze the task completion rates in the usability test',
      'create the usability testing report with recommendations',
    ],
  },
  {
    name: 'brand-guardian',
    agentSlug: 'design-brand-guardian',
    threshold: 0.72,
    fallbackToLLM: true,
    description: 'Brand consistency, visual identity, style guide',
    utterances: [
      'review the UI for brand consistency violations',
      'create the brand style guide for the new product',
      'update the color palette to match the new brand identity',
      'audit the marketing materials for brand guideline compliance',
      'create the logo usage guidelines and do-nots',
      'define the typography system for the brand',
      'create the brand voice and tone guidelines',
      'review the email templates for brand consistency',
    ],
  },
  {
    name: 'visual-storyteller',
    agentSlug: 'design-visual-storyteller',
    threshold: 0.70,
    fallbackToLLM: true,
    description: 'Visual storytelling, presentation design, data visualization',
    utterances: [
      'create compelling data visualizations for the annual report',
      'design the pitch deck for the investor presentation',
      'create the infographic explaining the product architecture',
      'design the visual narrative for the case study',
      'create the data story for the product metrics dashboard',
      'design the visual timeline for the company history',
      'create the product comparison chart design',
      'design the visual hierarchy for the marketing landing page',
    ],
  },
];
