import { Route } from '../types.js';

export const engineeringRoutes: Route[] = [
  {
    name: 'backend-architect',
    agentSlug: 'engineering-backend-architect',
    threshold: 0.70,
    fallbackToLLM: true,
    description: 'Backend system architecture, API design, microservices',
    utterances: [
      'design the backend architecture for the new service',
      'architect the microservices decomposition strategy',
      'design the event-driven backend for the order system',
      'create the API design for the user management service',
      'architect the database schema for multi-tenancy',
      'design the message queue topology for async processing',
      'plan the backend scalability strategy for 10x growth',
      'design the caching architecture for the read-heavy service',
      'architect the data pipeline for real-time analytics',
      'design the gRPC service contracts for inter-service communication',
    ],
  },
  {
    name: 'software-architect',
    agentSlug: 'engineering-software-architect',
    threshold: 0.70,
    fallbackToLLM: true,
    description: 'High-level software architecture, system design',
    utterances: [
      'design the overall system architecture for this application',
      'create an architecture decision record for this approach',
      'evaluate the architectural tradeoffs between these options',
      'design the hexagonal architecture for the domain layer',
      'define the bounded contexts for domain-driven design',
      'architect the CQRS and event sourcing implementation',
      'design the plugin architecture for extensibility',
      'create the technical design document for this system',
      'evaluate the monolith vs microservices tradeoff',
      'define the system integration patterns and contracts',
    ],
  },
  {
    name: 'frontend-developer',
    agentSlug: 'engineering-frontend-developer',
    threshold: 0.70,
    fallbackToLLM: true,
    description: 'Frontend development, React, UI components',
    utterances: [
      'build the React component for the user dashboard',
      'implement the frontend state management with Zustand',
      'create the responsive CSS layout for the landing page',
      'build the form validation logic for the checkout page',
      'implement the infinite scroll for the product list',
      'create the frontend routing with React Router',
      'build the data visualization charts for the analytics page',
      'implement the drag-and-drop interface for the kanban board',
      'optimize the frontend bundle size and loading performance',
      'build the real-time notification UI with WebSockets',
    ],
  },
  {
    name: 'devops-automator',
    agentSlug: 'engineering-devops-automator',
    threshold: 0.72,
    fallbackToLLM: true,
    description: 'CI/CD, infrastructure automation, DevOps pipelines',
    utterances: [
      'set up the GitHub Actions CI/CD pipeline',
      'configure the Kubernetes deployment manifests',
      'automate the infrastructure provisioning with Terraform',
      'set up Docker containerization for the services',
      'configure the monitoring and alerting with Prometheus',
      'automate the database backup and recovery process',
      'set up the staging environment deployment pipeline',
      'configure the auto-scaling rules for the ECS cluster',
      'implement the blue-green deployment strategy',
      'set up the secrets management with AWS Secrets Manager',
    ],
  },
  {
    name: 'data-engineer',
    agentSlug: 'engineering-data-engineer',
    threshold: 0.71,
    fallbackToLLM: true,
    description: 'Data pipelines, ETL, data warehousing, analytics',
    utterances: [
      'build the ETL pipeline for migrating data to the warehouse',
      'design the data model for the analytics dashboard',
      'implement the streaming data pipeline with Kafka',
      'create the data transformation jobs for the reporting layer',
      'build the data quality validation framework',
      'design the schema for the time-series metrics database',
      'implement the data lake ingestion pipeline',
      'create the aggregation queries for the business metrics',
      'optimize the slow analytical queries in the warehouse',
      'build the data lineage tracking system',
    ],
  },
  {
    name: 'ai-engineer',
    agentSlug: 'engineering-ai-engineer',
    threshold: 0.72,
    fallbackToLLM: true,
    description: 'AI/ML integration, LLM APIs, model deployment',
    utterances: [
      'integrate the OpenAI API for the chatbot feature',
      'implement the RAG pipeline for document Q&A',
      'build the prompt engineering framework for the AI assistant',
      'deploy the machine learning model as a REST API',
      'implement the vector database for semantic search',
      'build the fine-tuning pipeline for the custom model',
      'create the AI evaluation harness for model quality',
      'implement streaming responses from the LLM API',
      'build the multi-model routing for cost optimization',
      'create the AI agent orchestration system',
    ],
  },
  {
    name: 'sre',
    agentSlug: 'engineering-sre',
    threshold: 0.71,
    fallbackToLLM: true,
    description: 'Site reliability engineering, observability, incident response',
    utterances: [
      'define the SLOs and error budgets for the service',
      'set up distributed tracing with OpenTelemetry',
      'create the runbook for the database failover procedure',
      'implement chaos engineering tests for the system',
      'design the capacity planning model for traffic growth',
      'create the incident response playbook',
      'implement the health check endpoints for the services',
      'set up the log aggregation and search with ELK',
      'design the on-call rotation and escalation policy',
      'build the synthetic monitoring for critical user journeys',
    ],
  },
  {
    name: 'mobile-app-builder',
    agentSlug: 'engineering-mobile-app-builder',
    threshold: 0.72,
    fallbackToLLM: true,
    description: 'Mobile app development, React Native, iOS, Android',
    utterances: [
      'build the React Native screen for the user profile',
      'implement push notifications for the mobile app',
      'create the offline-first data sync for the iOS app',
      'build the deep linking implementation for the Android app',
      'implement biometric authentication in the mobile app',
      'create the app store listing assets and metadata',
      'build the in-app purchase flow for the mobile app',
      'implement the camera and image picker in React Native',
      'optimize the mobile app startup time and performance',
      'build the background location tracking feature',
    ],
  },
  {
    name: 'database-optimizer',
    agentSlug: 'engineering-database-optimizer',
    threshold: 0.71,
    fallbackToLLM: true,
    description: 'Database performance, query optimization, indexing',
    utterances: [
      'optimize the slow PostgreSQL query in the reporting module',
      'design the indexing strategy for the high-traffic tables',
      'analyze and fix the N+1 query problem in the ORM layer',
      'design the database partitioning strategy for the logs table',
      'optimize the database connection pool configuration',
      'create the database performance monitoring dashboard',
      'analyze the query execution plans and suggest improvements',
      'design the read replica strategy for the reporting workload',
      'implement the database migration with zero downtime',
      'optimize the full-text search index configuration',
    ],
  },
  {
    name: 'rapid-prototyper',
    agentSlug: 'engineering-rapid-prototyper',
    threshold: 0.68,
    fallbackToLLM: true,
    description: 'Rapid prototyping, proof of concept, MVP development',
    utterances: [
      'build a quick prototype to validate this concept',
      'create a proof of concept for the new feature',
      'build the MVP version of this application',
      'quickly scaffold the project structure',
      'create a demo to show to stakeholders',
      'prototype the user flow for the onboarding experience',
      'build a quick spike to test this approach',
      'create the minimal viable version of this API',
    ],
  },
];
