import { Route } from '../types.js';

export const gameDevRoutes: Route[] = [
  {
    name: 'game-designer',
    agentSlug: 'game-designer',
    threshold: 0.73,
    fallbackToLLM: true,
    description: 'Game design, mechanics, game systems design',
    utterances: [
      'design the core gameplay loop for the action RPG',
      'create the progression system for the mobile game',
      'design the economy and monetization system for the game',
      'create the combat mechanics design document',
      'design the tutorial flow for new player onboarding',
      'balance the difficulty curve for the puzzle levels',
      'design the multiplayer game modes and rules',
      'create the game design document for the new feature',
      'design the reward system for player retention',
      'balance the weapon stats for competitive fairness',
    ],
  },
  {
    name: 'unity-architect',
    agentSlug: 'unity-architect',
    threshold: 0.74,
    fallbackToLLM: true,
    description: 'Unity game development, C# scripting, Unity architecture',
    utterances: [
      'architect the Unity game systems for the new project',
      'implement the character controller in Unity',
      'optimize the Unity scene for better frame rate',
      'create the Unity editor tools for the content team',
      'implement the save system in Unity',
      'design the component architecture for the game objects',
      'optimize the Unity build size and loading times',
      'implement the Unity multiplayer with Netcode',
      'create the animation state machine in Unity',
      'implement the Unity addressables for asset management',
    ],
  },
  {
    name: 'godot-gameplay-scripter',
    agentSlug: 'godot-gameplay-scripter',
    threshold: 0.74,
    fallbackToLLM: true,
    description: 'Godot game development, GDScript, Godot architecture',
    utterances: [
      'implement the player movement in Godot with GDScript',
      'create the Godot state machine for the enemy AI',
      'implement the inventory system in Godot',
      'optimize the Godot scene tree structure',
      'create the Godot signals for game event communication',
      'implement the physics-based character controller in Godot',
      'create the Godot shader for the visual effect',
      'implement the Godot multiplayer with ENet',
    ],
  },
  {
    name: 'narrative-designer',
    agentSlug: 'narrative-designer',
    threshold: 0.72,
    fallbackToLLM: true,
    description: 'Game narrative, dialogue writing, world building, story design',
    utterances: [
      'write the branching dialogue for the NPC interaction',
      'design the narrative structure for the game campaign',
      'create the lore and world building for the game universe',
      'write the character backstories and motivations',
      'design the quest narrative and objectives',
      'create the in-game text for the environmental storytelling',
      'design the dialogue system and conversation trees',
      'write the game script for the cutscene sequences',
    ],
  },
  {
    name: 'level-designer',
    agentSlug: 'level-designer',
    threshold: 0.73,
    fallbackToLLM: true,
    description: 'Level design, map creation, environment design',
    utterances: [
      'design the level layout for the puzzle game stage',
      'create the encounter design for the dungeon level',
      'design the open world region with points of interest',
      'balance the level difficulty for the player skill curve',
      'design the platformer level with progressive challenges',
      'create the level metrics and flow analysis',
      'design the environmental hazards and obstacles',
      'create the level design document for the new zone',
    ],
  },
  {
    name: 'technical-artist',
    agentSlug: 'technical-artist',
    threshold: 0.73,
    fallbackToLLM: true,
    description: 'Technical art, shaders, VFX, art pipeline optimization',
    utterances: [
      'create the shader for the water surface rendering',
      'optimize the art asset pipeline for faster iteration',
      'implement the particle VFX system for the ability effects',
      'create the procedural texture generation system',
      'optimize the LOD system for the 3D assets',
      'implement the post-processing stack for the visual style',
      'create the rigging and skinning tools for the character art',
      'optimize the texture atlases and sprite sheets',
    ],
  },
];
