import { Route } from '../types.js';

export const marketingRoutes: Route[] = [
  {
    name: 'seo-specialist',
    agentSlug: 'marketing-seo-specialist',
    threshold: 0.72,
    fallbackToLLM: true,
    description: 'SEO optimization, keyword research, content strategy for search',
    utterances: [
      'optimize the landing page for search engine rankings',
      'perform keyword research for the product category',
      'audit the technical SEO issues on the website',
      'create the content strategy for improving organic traffic',
      'optimize the meta titles and descriptions for the blog posts',
      'build the internal linking strategy for the content hub',
      'analyze the backlink profile and create a link building plan',
      'optimize the page speed for better core web vitals scores',
      'create the schema markup for the product pages',
      'analyze competitors SEO strategy and find ranking opportunities',
    ],
  },
  {
    name: 'content-creator',
    agentSlug: 'marketing-content-creator',
    threshold: 0.70,
    fallbackToLLM: true,
    description: 'Content creation, copywriting, blog posts',
    utterances: [
      'write the blog post about the new product feature',
      'create the email newsletter for this month',
      'write the landing page copy for the product launch',
      'create the social media content calendar',
      'write the case study for the enterprise customer',
      'create the product description copy for the e-commerce page',
      'write the press release for the company announcement',
      'create the onboarding email sequence for new users',
      'write the help documentation for the new feature',
      'create the sales deck narrative and talking points',
    ],
  },
  {
    name: 'tiktok-strategist',
    agentSlug: 'marketing-tiktok-strategist',
    threshold: 0.75,
    fallbackToLLM: true,
    description: 'TikTok content strategy, viral content, short-form video',
    utterances: [
      'create a TikTok content strategy for the brand',
      'write TikTok video scripts for the product launch',
      'analyze TikTok trends to capitalize on for the brand',
      'create the TikTok hashtag strategy for discovery',
      'plan the TikTok influencer collaboration campaign',
      'optimize the TikTok posting schedule for maximum reach',
      'create the TikTok sound strategy for brand recall',
      'design the TikTok challenge concept for user participation',
    ],
  },
  {
    name: 'linkedin-content-creator',
    agentSlug: 'marketing-linkedin-content-creator',
    threshold: 0.75,
    fallbackToLLM: true,
    description: 'LinkedIn B2B content, thought leadership, professional networking',
    utterances: [
      'create the LinkedIn content strategy for the B2B brand',
      'write thought leadership posts for the company LinkedIn page',
      'create the LinkedIn newsletter for the industry insights',
      'write LinkedIn articles to build professional authority',
      'create the LinkedIn company page content calendar',
      'write the LinkedIn cold outreach message templates',
      'optimize the LinkedIn profile for the executive team',
      'create the LinkedIn event promotion content',
    ],
  },
  {
    name: 'growth-hacker',
    agentSlug: 'marketing-growth-hacker',
    threshold: 0.71,
    fallbackToLLM: true,
    description: 'Growth hacking, viral loops, user acquisition experiments',
    utterances: [
      'design the viral referral program for user acquisition',
      'create the growth experiment roadmap for Q3',
      'analyze the conversion funnel and identify improvement opportunities',
      'design the onboarding optimization to improve activation rates',
      'create the product-led growth strategy',
      'analyze cohort retention and design re-engagement campaigns',
      'design the A/B test framework for conversion optimization',
      'identify the viral coefficient and design growth loops',
      'create the growth metrics dashboard and KPI framework',
      'design the freemium to paid conversion optimization strategy',
    ],
  },
];
