import { Route } from '../types.js';

export const productRoutes: Route[] = [
  {
    name: 'product-manager',
    agentSlug: 'product-manager',
    threshold: 0.70,
    fallbackToLLM: true,
    description: 'Product management, requirements, roadmap planning',
    utterances: [
      'create the product requirements document for this feature',
      'prioritize the product backlog for the next sprint',
      'write the user stories for the new onboarding flow',
      'create the product roadmap for the next 6 months',
      'define the acceptance criteria for this feature',
      'analyze user feedback and synthesize product insights',
      'create the go-to-market plan for the product launch',
      'write the product specification for the API redesign',
      'analyze the competitive landscape for the product',
      'define the success metrics and KPIs for the feature',
    ],
  },
  {
    name: 'sprint-prioritizer',
    agentSlug: 'product-sprint-prioritizer',
    threshold: 0.71,
    fallbackToLLM: true,
    description: 'Sprint planning, backlog prioritization, capacity planning',
    utterances: [
      'prioritize the sprint backlog based on business value',
      'plan the next sprint with the engineering team capacity',
      'score the backlog items using RICE framework',
      'create the sprint goal and success criteria',
      'identify the dependencies between the backlog items',
      'balance the technical debt items with feature work in the sprint',
      'estimate the story points for the backlog items',
      'create the sprint retrospective action items',
    ],
  },
  {
    name: 'project-shepherd',
    agentSlug: 'project-management-project-shepherd',
    threshold: 0.70,
    fallbackToLLM: true,
    description: 'Project management, delivery tracking, risk management',
    utterances: [
      'track the project milestones and identify at-risk deliverables',
      'create the project status report for stakeholders',
      'identify and mitigate project risks and blockers',
      'manage the project scope and change control process',
      'create the project communication plan for the team',
      'track the project budget and resource utilization',
      'facilitate the project retrospective meeting',
      'create the resource allocation plan for the project',
      'manage the vendor relationships and deliverables',
      'create the project closure report and lessons learned',
    ],
  },
  {
    name: 'feedback-synthesizer',
    agentSlug: 'product-feedback-synthesizer',
    threshold: 0.71,
    fallbackToLLM: true,
    description: 'User feedback analysis, NPS analysis, customer insights',
    utterances: [
      'synthesize the customer support tickets into product insights',
      'analyze the NPS survey results and identify themes',
      'create the user feedback summary for the product team',
      'identify the most requested features from user feedback',
      'analyze the churn reasons from exit survey responses',
      'synthesize the beta tester feedback for the release decision',
      'create the customer satisfaction analysis report',
      'identify patterns in the user complaints and feature requests',
    ],
  },
];
