import { Route } from '../types.js';

export const securityRoutes: Route[] = [
  {
    name: 'security-engineer',
    agentSlug: 'engineering-security-engineer',
    threshold: 0.72,
    fallbackToLLM: true,
    description: 'Application security, vulnerability scanning, CVE analysis',
    utterances: [
      'audit the authentication system for vulnerabilities',
      'check for SQL injection risks in the API',
      'review JWT token handling and security',
      'scan for CVEs in npm dependencies',
      'implement input sanitization to prevent XSS',
      'find cross-site scripting vulnerabilities in the frontend',
      'review the OAuth flow for security issues',
      'check for privilege escalation paths in the role system',
      'validate CORS configuration against OWASP guidelines',
      'review cryptographic key management practices',
      'check for insecure direct object references in the endpoints',
      'audit the session management implementation',
      'review security headers in HTTP responses',
      'check for sensitive data exposure in API responses',
    ],
  },
  {
    name: 'security-architect',
    agentSlug: 'security-architect',
    threshold: 0.72,
    fallbackToLLM: true,
    description: 'Security architecture design, threat modeling',
    utterances: [
      'design a zero-trust security architecture',
      'create a threat model for the payment system',
      'design security boundaries between microservices',
      'architect the authentication and authorization system',
      'define the security posture for the new infrastructure',
      'design secrets management and rotation policies',
      'create a data classification and access control framework',
      'design the security monitoring and alerting architecture',
      'architect the network segmentation strategy',
      'define the cryptography standards and key hierarchy',
      'design the identity and access management system',
    ],
  },
  {
    name: 'security-auditor',
    agentSlug: 'security-auditor',
    threshold: 0.72,
    fallbackToLLM: true,
    description: 'Security audit, compliance review, penetration testing',
    utterances: [
      'perform a security audit of the codebase',
      'run a penetration test on the API endpoints',
      'audit the access control implementation for compliance',
      'review the application against OWASP Top 10',
      'conduct a security assessment of the infrastructure',
      'audit logging and monitoring for security events',
      'review the incident response procedures',
      'assess the risk of the third-party integrations',
      'audit the data retention and deletion policies',
      'review the disaster recovery security controls',
    ],
  },
  {
    name: 'blockchain-security-auditor',
    agentSlug: 'blockchain-security-auditor',
    threshold: 0.75,
    fallbackToLLM: true,
    description: 'Smart contract security, blockchain vulnerability analysis',
    utterances: [
      'audit the Solidity smart contract for reentrancy vulnerabilities',
      'check for integer overflow in the token contract',
      'review the ERC-20 implementation for security flaws',
      'audit the DeFi protocol for flash loan attack vectors',
      'check for front-running vulnerabilities in the DEX',
      'review the access control in the smart contract',
      'audit the oracle integration for manipulation risks',
      'check for gas optimization and DoS vectors in the contract',
      'review the upgradeable proxy pattern for security issues',
      'audit the multisig wallet implementation',
    ],
  },
  {
    name: 'threat-detection-engineer',
    agentSlug: 'engineering-threat-detection-engineer',
    threshold: 0.73,
    fallbackToLLM: true,
    description: 'Threat detection, SIEM, security monitoring',
    utterances: [
      'build the anomaly detection system for user behavior',
      'implement threat detection rules in the SIEM',
      'create alerts for suspicious API access patterns',
      'design the intrusion detection pipeline',
      'implement log correlation for threat identification',
      'build the security incident timeline reconstruction tool',
      'create detection signatures for known attack patterns',
      'implement real-time alerting for credential stuffing attacks',
    ],
  },
];
