import { Route } from '../types.js';

export const specializedRoutes: Route[] = [
  {
    name: 'mcp-builder',
    agentSlug: 'specialized-mcp-builder',
    threshold: 0.75,
    fallbackToLLM: true,
    description: 'MCP server development, tool integration, Claude extensions',
    utterances: [
      'build a new MCP server for the file system integration',
      'create the MCP tool definitions for the database operations',
      'implement the MCP transport layer for the custom server',
      'add new tools to the existing MCP server',
      'build the MCP server for the GitHub integration',
      'create the MCP schema validation for the tool inputs',
      'implement the MCP resource endpoints for the knowledge base',
      'debug the MCP connection issues in the Claude integration',
    ],
  },
  {
    name: 'compliance-auditor',
    agentSlug: 'compliance-auditor',
    threshold: 0.73,
    fallbackToLLM: true,
    description: 'Regulatory compliance, GDPR, SOC2, audit preparation',
    utterances: [
      'audit the application for GDPR compliance requirements',
      'prepare the evidence package for the SOC2 audit',
      'review the data processing agreements for compliance',
      'create the data retention policy documentation',
      'audit the privacy policy against current regulations',
      'prepare for the PCI-DSS compliance assessment',
      'review the third-party data sharing agreements',
      'create the compliance training materials for the team',
      'audit the access control logs for compliance reporting',
      'prepare the HIPAA compliance documentation',
    ],
  },
  {
    name: 'lsp-index-engineer',
    agentSlug: 'lsp-index-engineer',
    threshold: 0.76,
    fallbackToLLM: true,
    description: 'LSP server development, code intelligence, language tooling',
    utterances: [
      'build the LSP server for the custom language',
      'implement code completion in the language server',
      'add go-to-definition support to the LSP server',
      'implement the syntax highlighting grammar for the language',
      'build the symbol indexing for the code intelligence system',
      'optimize the LSP server response time for large codebases',
      'implement the reference finding in the language server',
      'create the diagnostic reporting for the LSP server',
    ],
  },
  {
    name: 'agents-orchestrator',
    agentSlug: 'agents-orchestrator',
    threshold: 0.70,
    fallbackToLLM: true,
    description: 'Multi-agent orchestration, swarm coordination, agent workflows',
    utterances: [
      'orchestrate a swarm of agents to complete the complex task',
      'coordinate the parallel execution of multiple specialized agents',
      'design the agent workflow for the multi-step process',
      'manage the handoff between agents in the pipeline',
      'orchestrate the research and implementation agents',
      'coordinate agents to build, test, and review the feature',
      'design the agent communication and memory sharing protocol',
      'manage the distributed task execution across the agent pool',
    ],
  },
  {
    name: 'salesforce-architect',
    agentSlug: 'specialized-salesforce-architect',
    threshold: 0.76,
    fallbackToLLM: true,
    description: 'Salesforce development, CRM customization, Apex development',
    utterances: [
      'design the Salesforce architecture for the CRM implementation',
      'write the Apex trigger for the opportunity update workflow',
      'create the Salesforce Flow for the lead routing process',
      'implement the Salesforce integration with the ERP system',
      'design the Salesforce custom objects for the data model',
      'optimize the SOQL queries in the Apex classes',
      'create the Lightning Web Components for the custom UI',
      'configure the Salesforce reports and dashboards',
    ],
  },
  {
    name: 'document-generator',
    agentSlug: 'specialized-document-generator',
    threshold: 0.70,
    fallbackToLLM: true,
    description: 'Technical documentation, API docs, architecture docs generation',
    utterances: [
      'generate the API documentation from the OpenAPI spec',
      'create the architecture document for the new system',
      'generate the README for the open source library',
      'create the technical specification document',
      'generate the database schema documentation',
      'create the deployment guide for the service',
      'generate the developer onboarding documentation',
      'create the changelog from the git commit history',
    ],
  },
];
