import { Route } from '../types.js';

export const testingRoutes: Route[] = [
  {
    name: 'accessibility-auditor',
    agentSlug: 'testing-accessibility-auditor',
    threshold: 0.73,
    fallbackToLLM: true,
    description: 'Accessibility testing, WCAG compliance, screen reader testing',
    utterances: [
      'audit the application for WCAG 2.1 compliance',
      'test the component with a screen reader for accessibility',
      'check the color contrast ratios against accessibility standards',
      'review the keyboard navigation flow for the form',
      'audit the ARIA attributes in the component library',
      'test the modal focus management for accessibility',
      'check the alt text on all images in the UI',
      'audit the touch target sizes for mobile accessibility',
      'review the accessibility of the data visualization charts',
      'test the application with VoiceOver and NVDA',
    ],
  },
  {
    name: 'api-tester',
    agentSlug: 'testing-api-tester',
    threshold: 0.72,
    fallbackToLLM: true,
    description: 'API testing, contract testing, endpoint validation',
    utterances: [
      'run API endpoint tests against the staging environment',
      'create contract tests for the provider and consumer APIs',
      'test the REST API for correct HTTP status codes',
      'validate the API response schemas against the OpenAPI spec',
      'write integration tests for the authentication endpoints',
      'test the API rate limiting behavior',
      'create load tests for the search API endpoint',
      'validate the pagination behavior in the list endpoints',
      'test the API error responses and error codes',
      'create the Postman collection for the API test suite',
    ],
  },
  {
    name: 'performance-benchmarker',
    agentSlug: 'testing-performance-benchmarker',
    threshold: 0.72,
    fallbackToLLM: true,
    description: 'Performance benchmarking, load testing, profiling',
    utterances: [
      'benchmark the response time of the database queries',
      'run load tests to determine the maximum throughput',
      'profile the memory usage of the caching layer',
      'benchmark the startup time of the application',
      'measure the CPU usage under peak load conditions',
      'create performance regression tests for the API',
      'run stress tests to find the breaking point of the service',
      'benchmark the vector search query performance',
      'measure the latency percentiles (p50, p95, p99) for the API',
      'profile the garbage collection behavior under load',
    ],
  },
  {
    name: 'reality-checker',
    agentSlug: 'testing-reality-checker',
    threshold: 0.70,
    fallbackToLLM: true,
    description: 'Production validation, smoke tests, health checks',
    utterances: [
      'validate the deployment worked correctly in production',
      'run smoke tests after the release to staging',
      'verify the critical user flows work in production',
      'check that all services are healthy after the deployment',
      'validate the database migrations ran successfully',
      'verify the feature flags are configured correctly',
      'check the payment flow works end-to-end in production',
      'validate the email delivery is working correctly',
      'verify the API is returning correct data after the migration',
      'check that monitoring and alerting are active',
    ],
  },
  {
    name: 'test-results-analyzer',
    agentSlug: 'testing-test-results-analyzer',
    threshold: 0.71,
    fallbackToLLM: true,
    description: 'Test result analysis, flaky test detection, coverage reporting',
    utterances: [
      'analyze the failing tests in the CI pipeline',
      'identify the flaky tests causing intermittent failures',
      'generate a test coverage report for the module',
      'analyze which tests are slowest and need optimization',
      'identify the missing test coverage in the critical paths',
      'analyze the test failure patterns across runs',
      'create a summary of the regression test results',
      'identify which tests are duplicating the same assertions',
      'analyze the end-to-end test failure root causes',
      'generate test quality metrics for the codebase',
    ],
  },
  {
    name: 'workflow-optimizer',
    agentSlug: 'testing-workflow-optimizer',
    threshold: 0.68,
    fallbackToLLM: true,
    description: 'Test workflow optimization, CI optimization, test parallelization',
    utterances: [
      'optimize the CI pipeline to reduce build time',
      'parallelize the test suite to speed up the feedback loop',
      'reorganize the test structure for better maintainability',
      'optimize the test database setup and teardown',
      'create the test sharding strategy for the large test suite',
      'reduce the test setup overhead with better fixtures',
      'optimize the end-to-end test execution time',
      'create the test tagging strategy for selective runs',
    ],
  },
];
